### ISSUE TITLE
Datajoint Works learn more link is broken on the welcome page

### ISSUE THREAD

**Issue by banchan86** [datajoint/datajoint-docs#84]

**Comment by MilagrosMarin** [comment]
Hi @banchan86,

Thank you for taking the time to report this issue! We’ve already fixed the broken link. If you encounter any other problems or have additional questions, feel free to reach out.

![Screenshot 2024-12-12 at 16 04 23](https://github.com/user-attachments/assets/007b53f8-ed0a-460c-838f-ca559da1eb0f)


Thanks again!
